const CATEGORY = {
  'species':
    [{'key':'lesliei','name':'紫勋'},
    {'key':'karasmontana','name':'花纹玉'},
    {'key':'schwantesii','name':'招福玉'},
    {'key':'hookeri','name':'富贵玉'},
    {'key':'julii','name':'寿丽玉'},
    {'key':'aucampiae','name':'日轮玉'},
    {'key':'pseudotruncatella','name':'曲玉'},
    {'key':'hallii','name':'巴里玉'},
    {'key':'optica','name':'大内玉'},
    {'key':'bromfieldii','name':'柘榴玉'},
    {'key':'verruculosa','name':'朝贡玉'},
    {'key':'terricolor','name':'碧琉璃'},
    {'key':'gracilidelineata','name':'荒玉'},
    {'key':'ruschiorum','name':'留蝶玉'},
    {'key':'fulviceps','name':'微纹玉'},
    {'key':'villetii','name':'丽典玉'},
    {'key':'salicola','name':'李夫人'},
    {'key':'marmorata','name':'茧形玉'},
    {'key':'vallis-mariae','name':'碧赐玉'},
    {'key':'dinteri','name':'神笛玉'},
    {'key':'herrei','name':'唐蓝玉'},
    {'key':'divergens','name':'宝翠玉'},
    {'key':'comptonii','name':'太古玉'},
    {'key':'otzeniana','name':'大津绘'},
    {'key':'meyeri','name':'菊水玉'},
    {'key':'olivacea','name':'橄榄玉'},
    {'key':'gesinae','name':'源氏玉'},
    {'key':'geyeri','name':'双眸玉'},
    {'key':'hermetica','name':'神秘玉'},
    {'key':'dorotheae','name':'丽虹玉'},
    {'key':'francisci','name':'古典玉'},
    {'key':'amicorum','name':'艾米玉'},
    {'key':'coleorum','name':'彩妍玉'},
    {'key':'helmutii','name':'青磁玉'},
    {'key':'naureeniae','name':'瑙琳玉'},
    {'key':'steineckeana','name':'翠娥'},
    {'key':'viridis','name':'美梨玉'},
    {'key':'werneri','name':'云映玉'}],
  'gardener':
    [{'key':'mesa','name':'Mesa Garden'},
    // {'key':'hammer','name':'哈默'},
    {'key':'fdp','name':'FDP'}]
}

module.exports = CATEGORY
